# Generated by Django 2.1.7 on 2019-03-15 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20190314_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='categary_id',
            new_name='categary',
        ),
    ]
